# Generated by Django 4.0.8 on 2023-01-10 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGameTag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('played_by', models.ManyToManyField(blank=True, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='games.boardgametag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
