# Generated by Django 4.0.8 on 2023-01-04 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('played_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
