# Generated by Django 4.0.8 on 2023-01-10 22:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='game_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgame',
            name='game_weight',
            field=models.DecimalField(decimal_places=2, default=3.45, max_digits=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgame',
            name='number_of_players',
            field=models.SmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
