# Generated by Django 4.0.8 on 2023-01-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_boardgame_played_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=models.ManyToManyField(related_name='games', to='games.gamecategory'),
        ),
    ]
