# Generated by Django 4.0.8 on 2023-01-10 22:50

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_boardgame_game_duration_boardgame_game_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='range_of_players',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(1, 6)),
            preserve_default=False,
        ),
    ]
