# Generated by Django 4.0.8 on 2023-01-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_boardgame_range_of_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='number_of_players',
        ),
    ]
