# Generated by Django 4.0.8 on 2023-01-09 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_gamecategory_boardgame_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecategory',
            options={'verbose_name_plural': 'game categories'},
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.gamecategory'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='played_by',
            field=models.ManyToManyField(blank=True, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
