# Generated by Django 4.0.8 on 2023-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_boardgame_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='game_duration_mins',
            field=models.PositiveBigIntegerField(default=45),
            preserve_default=False,
        ),
    ]
