# Generated by Django 4.0.8 on 2023-01-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_boardgame_game_duration_mins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='game_duration',
        ),
    ]
