# Generated by Django 4.0.8 on 2023-01-14 12:23

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_boardgame_game_duration_mins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='game_duration_range_mins',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(),
        ),
    ]
