# Generated by Django 4.0.8 on 2023-01-14 12:49

from django.db import migrations
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_boardgame_game_duration_range_mins'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='game_duration_mins',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(null=True),
        ),
    ]
