# Generated by Django 4.0.8 on 2023-01-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20230114_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='game_duration_range_mins',
        ),
    ]
