# Generated by Django 4.0.8 on 2023-01-14 20:59

from django.db import migrations
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_boardgame_range_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='game_duration_mins',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='range_of_players',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(),
        ),
    ]
