# Generated by Django 4.0.8 on 2023-01-16 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_boardgame_game_duration_mins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
