# Generated by Django 4.0.8 on 2023-01-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_boardgame_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={},
        ),
    ]
