# Generated by Django 4.0.8 on 2023-02-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_playedboardgame_boardgame_users_played_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playedboardgame',
            options={'ordering': ['-date_played', 'board_game', 'played_by']},
        ),
    ]
