# Generated by Django 4.0.8 on 2023-02-25 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_playedboardgame_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedboardgame',
            name='date_played',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
