# Generated by Django 4.0.8 on 2023-03-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_remove_boardgame_played_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['name']},
        ),
    ]
