# Generated by Django 4.0.8 on 2023-04-14 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_boardgame_board_game_geek_id_boardgame_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
