# Generated by Django 4.0.8 on 2023-04-16 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_boardgame_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
