# Generated by Django 4.0.8 on 2023-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='replayed_game_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
