# Generated by Django 4.2.7 on 2023-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_replayed_game_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
