# Generated by Django 4.2.7 on 2023-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_replayed_game_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
